print("Hello World!")
print("   /|")
print("  / |")
print(" /  |")
print("/___|")
print("")

print("")

print("\"Variables|'\"")

print("There once was a an named George, ")
print("hi was 70 years old. ")
print("He really liked the name George, ")
print("but didn't like being 70.")

character_name = "John"
character_age = "35"
print("___")
print("There once was a an named " + character_name + ", ")
print("he was " + character_age + " years old. ")
print("He really liked the name " + character_name + ", ")
print("but didn't like being " + character_name + ".")
print("___")
character_name = "Tom"
character_age = "50"
print("There once was a an named " + character_name + ", ")
print("he was " + character_age + " years old. ")
print("He really liked the name " + character_name + ", ")
print("but didn't like being " + character_name + ".")
print("___")
print("Different Types of Data that can be stored in Variables")
print("___")
print("\"Strings\"")
print("Plain Text")
print("Numbers - character age = 50. Decimals okay. No quotations needed")
print("Boolean- is_male = True  - notice Capitals for T/F in Boolean")

print("__")
print("\n")
print("\"Working with Strings\"")
print("Just plain Text - stored in a String")
print("Giraffe Academy")
print("Giraffe\nAcademy")
print("Giraffe\"Academy - escape character")
print("Giraffe\Academy")
print("\n")
print("\"String Variables\"")
phrase = "Giraffe Academy"
print(phrase)
print("\"Concatenation\" = Appending another String")
print(phrase + " is cool")
print("\"Common Functions - operate to modify or get information from strings\"")
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print("Indexing characters on a string, always start with zero")
print("Give a Function to a Value is called a \"paramater\"")
print(phrase.index("G"))
print(phrase.index("a"))
print(phrase.index("Acad"))
print(phrase.replace("Giraffe", "Elephant"))
print("___")
print("___")
print("GET COMFORTABLE WITH STRINGS - YOU WILL USE THEM LOTS!")
print("___")
print("___")
print("\"Working with Numbers\"")
print(2)
print(2.0987)
print(-2.0987)
print(3 + 4.5)
print(3 * 4.5)
print(3 * 4.5 + 5)
print(3 * (4.5 + 5))
print("Modulus Operator - spits out remainder of devision")
print(10 % 3)
my_num = 5
print(my_num)
print("\"Print numbers with text you need the str(my_num) phrase then +...")
print(str(my_num) + " my favorite number")
print("\"working with functions with numbers\"")
print("abs - absolute value")
print(pow(3, 2))
print(pow(4, 6))
print(max(4, 6))
print(min(4, 6))
print(round(3.2))
print('\"Import Python Math - to import external code')
from math import *
print(floor(3.7))
print(ceil(3.7))
print(sqrt(3.7))
print("___")
print("___")
print("\"Getting Input from User\"")
print("getting input from user and storing in a variable")
name = input("Enter your name: ")
age = input("Enter your age: ")
print("Hello " + name + "! You are " + age)
print("___")
print("___")
print("\"Building a Basic Calculator\"")
num1 = input("Enter a number: ")
num2 = input("Enter another number: ")
result = num1 + num2
print(result)
num1 = input("Enter a number: ")
num2 = input("Enter another number: ")
result = int(num1) + int(num2)
print(result)
num1 = input("Enter a number: ")
num2 = input("Enter another number: ")
result = float(num1) + float(num2)
print(result)




